// Shared vocabulary for the two budget-line editors: the internal manage view
// (BudgetEditor) and the grantee's draft view (PartnerBudgetEditor). Both render
// the same rows against the same server actions; only the surrounding chrome and
// what they're allowed to do differ.

import type { BudgetSection, BudgetLineCadence, InflationType } from "@/app/generated/prisma/client";

export type WorkingComp = { label: string; spec: string | null; qty: number; unitCost: number };
export type LineWorking = { components: WorkingComp[]; derivation: string | null; customised: boolean; frozen: boolean };
export type LineHistRow = { id: string; oldCost: number | null; newCost: number | null; source: string | null; changedBy: string | null; changedAt: string };

export type Line = {
  id: string;
  deliveryPartnerId: string | null;
  domain: string | null;
  section: BudgetSection;
  position: number;
  description: string;
  costCategory: InflationType;
  unitType: string;
  isAutoGenerated: boolean;
  salaryHint: string | null;
  notes: string | null;
  cadence: BudgetLineCadence;
  plannedMonths: number[];
  updatedAt?: string;
  y1Units: number; y1UnitCost: number; y1AllocPct: number; y1Total: number;
  y2Units: number; y2UnitCost: number; y2AllocPct: number; y2Total: number;
  y3Units: number; y3UnitCost: number; y3AllocPct: number; y3Total: number;
  y4Units: number; y4UnitCost: number; y4AllocPct: number; y4Total: number;
  y5Units: number; y5UnitCost: number; y5AllocPct: number; y5Total: number;
};

/** Where a budget sits in the share-with-the-grantee cycle. */
export type PartnerDraftState = {
  partnerEditState: "closed" | "open" | "submitted";
  partnerSharedAt?: string | null;
  partnerSubmittedAt?: string | null;
  partnerRound?: number;
  grantPartnerName?: string | null;
};

/** The budget fields both editors need. Each shell extends it with its own. */
export type BudgetCore = {
  id: string;
  name: string;
  domains: string[];
  years: number;
  horizonMonths: number;
  partialPosition?: "start" | "end";
  applyInflation: boolean;
  inflationSalaryPct: number;
  inflationOtherPct: number;
  inflationNilPct: number;
  status: "draft" | "final" | "approved";
  lines: Line[];
  domainLabels?: Record<string, string>;
  inputs?: Record<string, number | string | null> | null;
  workingByLineId?: Record<string, LineWorking>;
};

/** Inflation rate per category as a decimal, zeroed when the budget is flat. */
export function inflationRates(b: Pick<BudgetCore, "applyInflation" | "inflationSalaryPct" | "inflationOtherPct" | "inflationNilPct">): Record<InflationType, number> {
  return b.applyInflation
    ? { Salary: b.inflationSalaryPct / 100, Other: b.inflationOtherPct / 100, Nil: b.inflationNilPct / 100 }
    : { Salary: 0, Other: 0, Nil: 0 };
}

/** Whether the generator's count inputs were filled in — gates the total bars,
 *  which read as a meaningless ₹0 on a budget built line-by-line. */
export function hasCountInputs(inputs: BudgetCore["inputs"]): boolean {
  if (!inputs) return false;
  const { extraInputs, ...top } = inputs as Record<string, unknown>;
  const isCountEntry = ([k, v]: [string, unknown]) => k.startsWith("n") && typeof v === "number" && v > 0;
  return Object.entries(top).some(isCountEntry) ||
    (extraInputs != null && typeof extraInputs === "object" && Object.entries(extraInputs as Record<string, unknown>).some(isCountEntry));
}

export type BandKey = 1 | 2 | 3 | 4 | 5;
export type Band = { k: BandKey; factor: number; label: string };

/** Year-bands present in this horizon, including the pro-rated stub. The stub
 *  is the final band ("end") or Year 1 ("start"). */
export function computeBands(horizonMonths: number, partialPosition: "start" | "end" = "end"): Band[] {
  const fullYears = Math.floor(horizonMonths / 12);
  const tail      = horizonMonths - fullYears * 12;
  const out: Band[] = [];
  const totalBands = tail > 0 ? fullYears + 1 : fullYears;
  for (let k = 1 as BandKey; k <= 5; k = (k + 1) as BandKey) {
    if (k > totalBands) continue;
    if (tail > 0 && partialPosition === "start" && k === 1) {
      out.push({ k, factor: tail / 12, label: `Y1 (${tail}mo)` });
    } else if (tail > 0 && partialPosition === "end" && k === fullYears + 1) {
      out.push({ k, factor: tail / 12, label: `Y${k} (${tail}mo)` });
    } else {
      out.push({ k, factor: 1, label: `Y${k}` });
    }
  }
  return out;
}

export const yTotalKey = (k: BandKey) => `y${k}Total` as const;
export const yUnitsKey = (k: BandKey) => `y${k}Units` as const;
export const yCostKey  = (k: BandKey) => `y${k}UnitCost` as const;
export const yAllocKey = (k: BandKey) => `y${k}AllocPct` as const;

export const DOMAIN_LABELS: Record<string, string> = {
  Children: "Children", Youth: "Youth", Elderly: "Elderly + Kitchen",
  WelfareRights: "Welfare Rights", Creche: "Creche",
};

export const SECTION_LABELS: Record<BudgetSection, string> = {
  salary: "1. Salary & Honorarium",
  capex: "2. Fixed Assets / CAPEX",
  travel: "3. Travel",
  programme: "4. Programme Expenses",
  admin_salary: "5a. Admin – Salaries",
  admin_other: "5b. Admin – Other",
  additional: "6. Additional Items",
};

export const SECTION_ORDER: BudgetSection[] = ["salary", "capex", "travel", "programme", "admin_salary", "admin_other", "additional"];

export const INFLATION_BADGE: Record<InflationType, string> = {
  Salary: "bg-violet-100 text-violet-700",
  Other: "bg-sky-100 text-sky-700",
  Nil: "bg-stone-100 text-stone-500",
};

export const CADENCE_LABELS: Record<BudgetLineCadence, string> = {
  monthly: "Monthly",
  one_time: "One-time",
  seasonal: "Seasonal",
};

export const fmt = (n: number) => n === 0 ? "–" : `₹${n.toLocaleString("en-IN")}`;

/** Format a planned-months array as a short chip body: "M1" / "M3, M9". */
export const formatPlannedMonths = (months: number[]) =>
  months.length ? months.map(m => `M${m}`).join(", ") : "—";

export const horizonLabel = (m: number) =>
  m % 12 === 0 ? `${m / 12}-year` : `${m}-month`;
