"use server";

import { auth } from "@/lib/auth";
import { isBudgetAdminOrSuperAdmin } from "@/lib/roleGuard";
import { requireBudgetAccess, withBudgetLineWrite, type BudgetLineWrite } from "@/lib/budget/budgetAccess";
import { assertPartnerEditClosed } from "@/lib/budget/partnerDraft";
import { requireGrantingUnit } from "@/lib/budget/grantingUnits";
import { resolveRegistryRows, resolveRegistryComponents } from "@/lib/budget/costRegistry";
import prisma from "@/lib/prisma";
import bcrypt from "bcryptjs";
import { randomBytes } from "crypto";
import { sendPartnerInviteEmail } from "@/lib/email";
import { generateBudgetLines, DEFAULT_INFLATION_RATES, activeYearBands } from "@/lib/budget-generator";
import type { BudgetSection, BudgetLineCadence, InflationType } from "@/app/generated/prisma/client";
import { redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import type { ParsedBudget } from "@/lib/budget/importTemplate";

export type CreateBudgetPayload = {
  name: string;
  city: string;
  /** Grantee org (GrantPartner.id) this budget belongs to. Null = unassigned. */
  grantPartnerId?: string | null;
  domains: string[];
  horizonMonths: number;
  /** Where the pro-rated stub sits: "start" or "end" (default). */
  partialPosition?: "start" | "end";
  applyInflation: boolean;
  programmeInputs: Record<string, number>;
  includeCrossCutting: boolean;
  /** Sparse delta keyed by CostRegistry.itemKey. {} when partner picked "Standard". */
  costOverrides?: Record<string, number>;
  /**
   * Multi-partner mode. When 2+ delivery partners are given, each gets its own
   * domain lines from its own programmeInputs (tagged deliveryPartnerId), the
   * budget's inputs become the summed totals, and cross-cutting lines are
   * generated once into the Master (deliveryPartnerId null). sharedPct is each
   * partner's explicit share of those shared costs (consumed at display/export).
   * grantPartnerId links each delivery-partner tab to the same GrantPartner
   * registry as Budget.grantPartnerId; name is the display label (usually the
   * partner's name at save-time — kept denormalised so the tab still labels
   * correctly if the registry row is later renamed or unlinked).
   */
  deliveryPartners?: { name: string; sharedPct: number; grantPartnerId?: string | null; programmeInputs: Record<string, number> }[];
};

/** Element-wise sum of several flat input maps (for the master totals). */
function sumInputs(maps: Record<string, number>[]): Record<string, number> {
  const out: Record<string, number> = {};
  for (const m of maps) for (const [k, v] of Object.entries(m)) out[k] = (out[k] ?? 0) + (Number(v) || 0);
  return out;
}

/** Nested-create payload for a BudgetInputs row from a flat input map. */
function buildInputsCreate(pi: Record<string, number>) {
  return {
    nSettlements:              Math.round(pi.nSettlements ?? 0),
    nClusters:                 Math.round(pi.nClusters ?? 0),
    nCLCs:                     Math.round(pi.nCLCs ?? 0),
    clcRentPerMonth:           Math.round(pi.clcRentPerMonth ?? 0),
    nYRCs:                     Math.round(pi.nYRCs ?? 0),
    yrcRentPerMonth:           Math.round(pi.yrcRentPerMonth ?? 0),
    nElderlyCentres:           Math.round(pi.nElderlyCentres ?? 0),
    nElderly:                  Math.round(pi.nElderly ?? 0),
    elderlyCentreRentPerMonth: Math.round(pi.elderlyCentreRentPerMonth ?? 0),
    cosPerCluster:             Math.round(pi.cosPerCluster ?? 0),
    rcRentPerMonth:            Math.round(pi.rcRentPerMonth ?? 0),
    nCreches:                  Math.round(pi.nCreches ?? 0),
    crecheRentPerMonth:        Math.round(pi.crecheRentPerMonth ?? 0),
    extraInputs:               pi,
  };
}

/** Flat per-line column data from a generated line (no budgetId/partner). */
function lineCreateData(l: ReturnType<typeof generateBudgetLines>[number]) {
  return {
    domain: l.domain ?? undefined,
    section: l.section,
    position: l.position,
    description: l.description,
    costCategory: l.costCategory,
    unitType: l.unitType,
    isAutoGenerated: l.isAutoGenerated ?? true,
    salaryHint: l.salaryHint,
    notes: l.notes,
    templateKey: l.templateKey,
    cadence: l.cadence,
    plannedMonths: l.plannedMonths,
    y1Units: l.y1Units, y1UnitCost: l.y1UnitCost, y1AllocPct: l.y1AllocPct, y1Total: l.y1Total,
    y2Units: l.y2Units, y2UnitCost: l.y2UnitCost, y2AllocPct: l.y2AllocPct, y2Total: l.y2Total,
    y3Units: l.y3Units, y3UnitCost: l.y3UnitCost, y3AllocPct: l.y3AllocPct, y3Total: l.y3Total,
    y4Units: l.y4Units, y4UnitCost: l.y4UnitCost, y4AllocPct: l.y4AllocPct, y4Total: l.y4Total,
    y5Units: l.y5Units, y5UnitCost: l.y5UnitCost, y5AllocPct: l.y5AllocPct, y5Total: l.y5Total,
  };
}

// ── Grant partners (grantee orgs) ───────────────────────────────────────────

export async function listGrantPartners(city: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  return prisma.grantPartner.findMany({
    where: { city, isActive: true },
    orderBy: { name: "asc" },
    select: { id: true, name: true },
  });
}

/** Create-or-return a partner for a granting unit (idempotent on [grantingUnitId, name]). */
export async function createGrantPartner(city: string, name: string): Promise<{ id: string; name: string }> {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const trimmed = name.trim();
  if (!trimmed) throw new Error("Partner name required");
  const unit = await requireGrantingUnit(city);
  const gp = await prisma.grantPartner.upsert({
    where: { grantingUnitId_name: { grantingUnitId: unit.id, name: trimmed } },
    create: { city: unit.name, grantingUnitId: unit.id, name: trimmed },
    update: { isActive: true },
    select: { id: true, name: true },
  });
  revalidatePath("/budget/dashboard");
  revalidatePath("/budget/admin/partners");
  return gp;
}

export async function renameGrantPartner(id: string, name: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const trimmed = name.trim();
  if (!trimmed) throw new Error("Partner name required");
  await prisma.grantPartner.update({ where: { id }, data: { name: trimmed } });
  revalidatePath("/budget/admin/partners");
  revalidatePath("/budget/dashboard");
}

export async function toggleGrantPartner(id: string, isActive: boolean) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  await prisma.grantPartner.update({ where: { id }, data: { isActive } });
  revalidatePath("/budget/admin/partners");
}

/** Move a partner (and all its budgets) to another granting unit. Keeps the
 *  partner↔budget invariant intact by migrating both together. Refuses if a
 *  partner of the same name already lives in the target unit (the
 *  [grantingUnitId, name] unique). Budget-admin/super-admin only. */
export async function reassignGrantPartnerCity(partnerId: string, newCity: string): Promise<{ movedBudgets: number }> {
  const session = await auth();
  if (!isBudgetAdminOrSuperAdmin(session)) throw new Error("Forbidden");
  const unit = await requireGrantingUnit(newCity.trim());
  const city = unit.name;

  const gp = await prisma.grantPartner.findUnique({ where: { id: partnerId }, select: { name: true, city: true } });
  if (!gp) throw new Error("Partner not found");
  if (gp.city === city) return { movedBudgets: 0 };

  const clash = await prisma.grantPartner.findUnique({
    where: { grantingUnitId_name: { grantingUnitId: unit.id, name: gp.name } },
    select: { id: true },
  });
  if (clash) throw new Error(`A partner named "${gp.name}" already exists in ${city}. Rename or merge it there first.`);

  const movedBudgets = await prisma.$transaction(async (tx) => {
    await tx.grantPartner.update({ where: { id: partnerId }, data: { city, grantingUnitId: unit.id } });
    const res = await tx.budget.updateMany({ where: { grantPartnerId: partnerId }, data: { city, grantingUnitId: unit.id } });
    return res.count;
  });

  revalidatePath("/budget/admin/partners");
  revalidatePath("/budget/dashboard");
  revalidatePath("/budget");
  return { movedBudgets };
}

// Add an existing user account as one of this grantee's logins (role
// "partner"). The account must be created first in Settings → Users. Only
// promotes a plain member/viewer/partner — never touches an
// admin/super-admin/budget-admin.
export async function linkGrantPartnerLogin(partnerId: string, email: string): Promise<{ email: string }> {
  const session = await auth();
  if (!isBudgetAdminOrSuperAdmin(session)) throw new Error("Forbidden");
  const normalized = email.trim().toLowerCase();
  if (!normalized) throw new Error("Email required");
  const user = await prisma.user.findFirst({
    where: { email: { equals: normalized, mode: "insensitive" } },
    select: { id: true, email: true, role: true },
  });
  if (!user) throw new Error("No user with that email. Create the account in Settings → Users first, then link it here.");

  const PROMOTABLE = ["member", "viewer", "partner"];
  await prisma.$transaction(async (tx) => {
    // Still one grantee per login — moving an account re-points it rather than
    // giving that person sight of two grantees' budgets.
    await tx.grantPartnerUser.upsert({
      where: { userId: user.id },
      create: { userId: user.id, grantPartnerId: partnerId },
      update: { grantPartnerId: partnerId },
    });
    if (PROMOTABLE.includes(user.role)) {
      await tx.user.update({ where: { id: user.id }, data: { role: "partner" } });
    }
  });
  revalidatePath("/budget/admin/partners");
  return { email: user.email };
}

/**
 * Create a login for a grantee contact and email them a link to set a password.
 *
 * Invite-only, deliberately: this portal holds signed financial declarations, so
 * an account is never self-created. The token reuses the password-reset table
 * with a longer window — an NGO's finance contact will not read their inbox
 * inside the reset flow's hour.
 */
export async function inviteGrantPartnerLogin(
  partnerId: string,
  email: string,
  name?: string,
): Promise<{ email: string }> {
  const session = await auth();
  if (!isBudgetAdminOrSuperAdmin(session)) throw new Error("Forbidden");

  const normalized = email.trim().toLowerCase();
  if (!/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(normalized)) throw new Error("Enter a valid email address");

  const partner = await prisma.grantPartner.findUnique({ where: { id: partnerId }, select: { name: true } });
  if (!partner) throw new Error("Grantee not found");

  const existing = await prisma.user.findFirst({
    where: { email: { equals: normalized, mode: "insensitive" } },
    select: { id: true, role: true },
  });
  // An internal colleague must never be turned into an external grantee login.
  if (existing && !["member", "viewer", "partner"].includes(existing.role)) {
    throw new Error("That account belongs to an internal user. Link a separate address for the grantee.");
  }

  const INVITE_DAYS = 14;
  const token = randomBytes(32).toString("hex");
  // Hashed outside the transaction — bcrypt is deliberately slow and would hold
  // the connection open for no reason.
  const placeholderPassword = await bcrypt.hash(randomBytes(32).toString("hex"), 10);

  await prisma.$transaction(async (tx) => {
    const userId = existing
      ? (await tx.user.update({ where: { id: existing.id }, data: { role: "partner" }, select: { id: true } })).id
      : (
          await tx.user.create({
            data: {
              email: normalized,
              name: name?.trim() || normalized,
              // Unusable until they set one through the invite link.
              password: placeholderPassword,
              role: "partner",
            },
            select: { id: true },
          })
        ).id;

    await tx.grantPartnerUser.upsert({
      where: { userId },
      create: { userId, grantPartnerId: partnerId },
      update: { grantPartnerId: partnerId },
    });

    await tx.passwordResetToken.deleteMany({ where: { email: normalized } });
    await tx.passwordResetToken.create({
      data: { email: normalized, token, expiresAt: new Date(Date.now() + INVITE_DAYS * 86400000) },
    });
  });

  await sendPartnerInviteEmail(normalized, token, {
    orgName: partner.name,
    invitedBy: session?.user?.name ?? null,
    expiresInDays: INVITE_DAYS,
  });

  revalidatePath("/budget/admin/partners");
  return { email: normalized };
}

export async function unlinkGrantPartnerLogin(userId: string) {
  const session = await auth();
  if (!isBudgetAdminOrSuperAdmin(session)) throw new Error("Forbidden");
  await prisma.grantPartnerUser.deleteMany({ where: { userId } });
  revalidatePath("/budget/admin/partners");
}

/** One-way import: copy every active Settings → Partners org (Org kind="partner")
 *  into GrantPartner for the given granting unit. Idempotent on
 *  [grantingUnitId, name]; existing
 *  rows are left untouched (and reactivated if they were deactivated). Returns
 *  how many were newly created. */
export async function importGrantPartnersFromOrgs(city: string): Promise<{ added: number; total: number }> {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const unit = await requireGrantingUnit(city.trim());
  const trimmedCity = unit.name;

  const orgs = await prisma.org.findMany({
    where: { kind: "partner", archivedAt: null },
    select: { name: true },
    orderBy: { name: "asc" },
  });

  let added = 0;
  for (const o of orgs) {
    const name = o.name.trim();
    if (!name) continue;
    const existing = await prisma.grantPartner.findUnique({
      where: { grantingUnitId_name: { grantingUnitId: unit.id, name } },
      select: { id: true },
    });
    if (existing) continue;
    await prisma.grantPartner.create({ data: { city: trimmedCity, grantingUnitId: unit.id, name } });
    added++;
  }

  revalidatePath("/budget/admin/partners");
  revalidatePath("/budget/dashboard");
  return { added, total: orgs.length };
}

/** (Re)assign a budget to a grantee org, or unassign (null). Owner-only; the
 *  partner must belong to the same city as the budget. */
export async function updateBudgetGrantPartner(budgetId: string, grantPartnerId: string | null) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true, grantPartnerId: true, city: true } });
  await requireBudgetAccess(session, budget, "update");
  if (!budget) throw new Error("Not found");

  if (grantPartnerId) {
    const gp = await prisma.grantPartner.findUnique({ where: { id: grantPartnerId }, select: { city: true } });
    if (!gp || gp.city !== budget.city) throw new Error("Partner is not in this budget's city");
  }

  await prisma.budget.update({ where: { id: budgetId }, data: { grantPartnerId } });
  revalidatePath(`/budget/${budgetId}`);
  revalidatePath("/budget/dashboard");
}

/** (Re)assign the accountable grant lead, or clear it (null). */
export async function updateBudgetGrantLead(budgetId: string, grantLeadId: string | null) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true, grantPartnerId: true } });
  await requireBudgetAccess(session, budget, "update");

  if (grantLeadId) {
    // A grantee's own login must never become the internal lead — they'd start
    // receiving the chase-the-partner side of the reminder flow.
    const u = await prisma.user.findUnique({ where: { id: grantLeadId }, select: { role: true } });
    if (!u || u.role === "partner") throw new Error("Not a valid grant lead");
  }

  await prisma.budget.update({ where: { id: budgetId }, data: { grantLeadId } });
  revalidatePath(`/budget/${budgetId}`);
  revalidatePath("/budget/dashboard");
}

/**
 * Freeze each generated line's "working": snapshot the standard registry
 * component breakup (+ derivation) onto the line so the budget carries a
 * faithful point-in-time record (immune to later registry changes). Left
 * workingCustomised=false — a create-time cost override changes the COST, not
 * the working, and the reconcile ⚠ already flags where the frozen standard
 * breakup no longer sums to the line's cost. Also logs a "generated at ₹X"
 * origin entry per costed line.
 */
async function snapshotLineWorking(
  budgetId: string,
  sourceCity: string,
  templates: { templateKey: string; costKey: string | null }[],
  changedById: string,
) {
  const [compByKey, regItems, lines] = await Promise.all([
    resolveRegistryComponents(sourceCity),
    resolveRegistryRows(sourceCity),
    prisma.budgetLine.findMany({ where: { budgetId }, select: { id: true, templateKey: true, y1UnitCost: true } }),
  ]);
  const derivByKey = new Map(regItems.map(r => [r.itemKey, r.derivation]));
  const costKeyByTemplate = new Map(templates.map(t => [t.templateKey, t.costKey]));

  const componentRows: { budgetLineId: string; position: number; label: string; spec: string | null; qty: number; unitCost: number }[] = [];
  const historyRows: { budgetLineId: string; oldCost: null; newCost: number; source: string; changedById: string }[] = [];
  const derivUpdates: { id: string; derivation: string }[] = [];

  for (const l of lines) {
    if (l.y1UnitCost > 0) historyRows.push({ budgetLineId: l.id, oldCost: null, newCost: l.y1UnitCost, source: "generated", changedById });
    const costKey = l.templateKey ? costKeyByTemplate.get(l.templateKey) ?? null : null;
    if (!costKey) continue;
    const cs = compByKey[costKey];
    if (!cs || cs.length === 0) continue;
    cs.forEach((c, i) => componentRows.push({ budgetLineId: l.id, position: i, label: c.label, spec: c.spec, qty: c.qty, unitCost: c.unitCost }));
    const d = derivByKey.get(costKey);
    if (d) derivUpdates.push({ id: l.id, derivation: d });
  }

  if (componentRows.length) await prisma.budgetLineComponent.createMany({ data: componentRows });
  if (historyRows.length) await prisma.budgetLineCostHistory.createMany({ data: historyRows });
  for (const u of derivUpdates) await prisma.budgetLine.update({ where: { id: u.id }, data: { derivation: u.derivation } });
}

export async function createBudget(payload: CreateBudgetPayload) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const horizonMonths = Math.min(60, Math.max(1, Math.round(payload.horizonMonths)));
  const partialPosition: "start" | "end" = payload.partialPosition === "start" ? "start" : "end";
  // Keep `years` in sync for legacy read paths (list pages, report-actions
  // grantYear lookups, etc.). years = number of year-bands the horizon covers.
  const years = activeYearBands(horizonMonths);

  // A unit like "Others" has no CostRegistry or LineTemplate rows of its own;
  // it generates from whichever standard set its `registryCity` points at, so
  // the generator produces non-zero lines. Budget.city keeps the unit's own name
  // so the budget stays under that unit's tab.
  const unit = await requireGrantingUnit(payload.city);
  const sourceCity = unit.registryCity;
  const [registryRows, templates] = await Promise.all([
    resolveRegistryRows(sourceCity),
    prisma.lineTemplate.findMany({ where: { city: sourceCity }, orderBy: { position: "asc" } }),
  ]);
  // Snapshot the full registry at create time. Stored on Budget.costSnapshot
  // so future regenerate / scale-up actions reproduce the partner's basis
  // even if the registry has since changed.
  const costSnapshot: Record<string, number> = Object.fromEntries(registryRows.map(r => [r.itemKey, r.unitCost]));
  // Drop overrides for keys not in the registry so we never persist orphan keys.
  const rawOverrides = payload.costOverrides ?? {};
  const costOverrides: Record<string, number> = {};
  for (const [k, v] of Object.entries(rawOverrides)) {
    if (typeof v === "number" && Number.isFinite(v) && k in costSnapshot) {
      costOverrides[k] = v;
    }
  }
  // Generator reads snapshot ∪ overrides — overrides win where present.
  const mergedRegistry: Record<string, number> = { ...costSnapshot, ...costOverrides };

  const genOpts = { horizonMonths, applyInflation: payload.applyInflation, inflationRates: DEFAULT_INFLATION_RATES, partialPosition };

  // ── Multi-partner path ──────────────────────────────────────────────────────
  const partners = (payload.deliveryPartners ?? []).filter(p => p.name?.trim());
  if (partners.length >= 2) {
    const summed = sumInputs(partners.map(p => p.programmeInputs));
    const directTemplates = templates.filter(t => t.domain !== null);
    const sharedTemplates = templates.filter(t => t.domain === null);

    // Enforce the same-city invariant as Budget.grantPartnerId. Any invalid
    // link is silently dropped (name still carries the label) — we don't want
    // a stray registry pick to block a whole budget create.
    const linkedIds = Array.from(new Set(partners.map(p => p.grantPartnerId).filter((x): x is string => !!x)));
    const validLinkedIds = new Set<string>();
    if (linkedIds.length) {
      const validRows = await prisma.grantPartner.findMany({
        where: { id: { in: linkedIds }, city: payload.city },
        select: { id: true },
      });
      for (const r of validRows) validLinkedIds.add(r.id);
    }

    // Each partner's domain lines come from its own inputs; shared/cross-cutting
    // lines are generated once from the summed totals into the Master.
    const perPartnerLines = partners.map(p =>
      generateBudgetLines(payload.domains, p.programmeInputs, genOpts, mergedRegistry, directTemplates));
    const sharedLines = payload.includeCrossCutting
      ? generateBudgetLines(payload.domains, summed, genOpts, mergedRegistry, sharedTemplates)
      : [];

    const budget = await prisma.budget.create({
      data: {
        name: payload.name, city: payload.city, grantingUnitId: unit.id, partnerId: session.user.id,
        grantPartnerId: payload.grantPartnerId ?? null,
        domains: payload.domains, years, horizonMonths, partialPosition,
        applyInflation: payload.applyInflation, costSnapshot, costOverrides,
        isMultiPartner: true,
        inputs: { create: buildInputsCreate(summed) },
        deliveryPartners: {
          create: partners.map((p, i) => ({
            name: p.name.trim(), sortOrder: i,
            sharedPct: Number.isFinite(p.sharedPct) ? p.sharedPct : 0,
            grantPartnerId: p.grantPartnerId && validLinkedIds.has(p.grantPartnerId) ? p.grantPartnerId : null,
            inputs: p.programmeInputs,
          })),
        },
      },
      include: { deliveryPartners: true },
    });

    const idByOrder = new Map(budget.deliveryPartners.map(dp => [dp.sortOrder, dp.id]));
    const lineRows = [
      ...perPartnerLines.flatMap((ls, i) => ls.map(l => ({ ...lineCreateData(l), budgetId: budget.id, deliveryPartnerId: idByOrder.get(i) ?? null }))),
      ...sharedLines.map(l => ({ ...lineCreateData(l), budgetId: budget.id, deliveryPartnerId: null })),
    ];
    if (lineRows.length) await prisma.budgetLine.createMany({ data: lineRows });

    await snapshotLineWorking(budget.id, sourceCity, templates, session.user.id);
    redirect(`/budget/${budget.id}`);
  }

  const eligibleTemplates = payload.includeCrossCutting
    ? templates
    : templates.filter(t => t.domain !== null);
  const lines = generateBudgetLines(
    payload.domains,
    payload.programmeInputs,
    genOpts,
    mergedRegistry,
    eligibleTemplates,
  );

  const pi = payload.programmeInputs;
  const budget = await prisma.budget.create({
    data: {
      name: payload.name,
      city: payload.city,
      grantingUnitId: unit.id,
      partnerId: session.user.id,
      grantPartnerId: payload.grantPartnerId ?? null,
      domains: payload.domains,
      years,
      horizonMonths,
      partialPosition,
      applyInflation: payload.applyInflation,
      costSnapshot,
      costOverrides,
      // Inflation rates fall back to the Prisma schema defaults (10/5/0) if omitted.
      inputs: {
        create: {
          // Keep typed fields populated for backward compat with existing queries
          nSettlements:              Math.round(pi.nSettlements ?? 0),
          nClusters:                 Math.round(pi.nClusters ?? 0),
          nCLCs:                     Math.round(pi.nCLCs ?? 0),
          clcRentPerMonth:           Math.round(pi.clcRentPerMonth ?? 0),
          nYRCs:                     Math.round(pi.nYRCs ?? 0),
          yrcRentPerMonth:           Math.round(pi.yrcRentPerMonth ?? 0),
          nElderlyCentres:           Math.round(pi.nElderlyCentres ?? 0),
          nElderly:                  Math.round(pi.nElderly ?? 0),
          elderlyCentreRentPerMonth: Math.round(pi.elderlyCentreRentPerMonth ?? 0),
          cosPerCluster:             Math.round(pi.cosPerCluster ?? 0),
          rcRentPerMonth:            Math.round(pi.rcRentPerMonth ?? 0),
          nCreches:                  Math.round(pi.nCreches ?? 0),
          crecheRentPerMonth:        Math.round(pi.crecheRentPerMonth ?? 0),
          extraInputs:               pi,  // full flat map — source of truth going forward
        },
      },
      lines: {
        create: lines.map(l => ({
          domain: l.domain ?? undefined,
          section: l.section,
          position: l.position,
          description: l.description,
          costCategory: l.costCategory,
          unitType: l.unitType,
          isAutoGenerated: l.isAutoGenerated ?? true,
          salaryHint: l.salaryHint,
          notes: l.notes,
          templateKey: l.templateKey,
          cadence: l.cadence,
          plannedMonths: l.plannedMonths,
          y1Units: l.y1Units,
          y1UnitCost: l.y1UnitCost,
          y1AllocPct: l.y1AllocPct,
          y1Total: l.y1Total,
          y2Units: l.y2Units,
          y2UnitCost: l.y2UnitCost,
          y2AllocPct: l.y2AllocPct,
          y2Total: l.y2Total,
          y3Units: l.y3Units,
          y3UnitCost: l.y3UnitCost,
          y3AllocPct: l.y3AllocPct,
          y3Total: l.y3Total,
          y4Units: l.y4Units,
          y4UnitCost: l.y4UnitCost,
          y4AllocPct: l.y4AllocPct,
          y4Total: l.y4Total,
          y5Units: l.y5Units,
          y5UnitCost: l.y5UnitCost,
          y5AllocPct: l.y5AllocPct,
          y5Total: l.y5Total,
        })),
      },
    },
  });

  await snapshotLineWorking(budget.id, sourceCity, templates, session.user.id);
  redirect(`/budget/${budget.id}`);
}

/**
 * Create a budget from a parsed (imported) Excel template. Mirrors createBudget's
 * write but uses the parsed lines/inputs verbatim instead of the generator, and
 * stamps importedAt so a future "regenerate from inputs" knows the lines carry
 * hand edits. Returns the new id (no redirect) so the client can navigate.
 */
export async function createBudgetFromImport(
  parsed: ParsedBudget,
  opts?: { city?: string; grantPartnerId?: string | null },
): Promise<{ id: string }> {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const horizonMonths = Math.min(60, Math.max(1, Math.round(parsed.horizonMonths || 12)));
  const years = activeYearBands(horizonMonths);
  const pi = parsed.inputs ?? {};
  const num = (k: string) => Math.round(Number(pi[k]) || 0);
  const unit = await requireGrantingUnit(opts?.city?.trim() || parsed.city);

  const budget = await prisma.budget.create({
    data: {
      name: parsed.name,
      city: unit.name,
      grantingUnitId: unit.id,
      grantPartnerId: opts?.grantPartnerId ?? null,
      partnerId: session.user.id,
      domains: parsed.domains,
      years,
      horizonMonths,
      applyInflation: parsed.applyInflation,
      inflationSalaryPct: parsed.inflationPct.Salary,
      inflationOtherPct: parsed.inflationPct.Other,
      inflationNilPct: parsed.inflationPct.Nil,
      costSnapshot: parsed.costSnapshot,
      costOverrides: parsed.costOverrides,
      importedAt: new Date(),
      inputs: {
        create: {
          nSettlements: num("nSettlements"), nClusters: num("nClusters"),
          nCLCs: num("nCLCs"), clcRentPerMonth: num("clcRentPerMonth"),
          nYRCs: num("nYRCs"), yrcRentPerMonth: num("yrcRentPerMonth"),
          nElderlyCentres: num("nElderlyCentres"), nElderly: num("nElderly"),
          elderlyCentreRentPerMonth: num("elderlyCentreRentPerMonth"),
          cosPerCluster: num("cosPerCluster"), rcRentPerMonth: num("rcRentPerMonth"),
          nCreches: num("nCreches"), crecheRentPerMonth: num("crecheRentPerMonth"),
          extraInputs: pi,
        },
      },
      lines: {
        create: parsed.lines
          .slice()
          .sort((a, b) => a.position - b.position)
          .map((l, i) => ({
            domain: l.domain ?? undefined,
            section: l.section as BudgetSection,
            position: i,
            description: l.description,
            costCategory: l.costCategory as InflationType,
            unitType: l.unitType,
            isAutoGenerated: false,
            salaryHint: l.salaryHint,
            notes: l.notes,
            templateKey: l.templateKey,
            cadence: l.cadence as BudgetLineCadence,
            plannedMonths: l.plannedMonths,
            y1Units: l.y1Units, y1UnitCost: l.y1UnitCost, y1AllocPct: l.y1AllocPct, y1Total: l.y1Total,
            y2Units: l.y2Units, y2UnitCost: l.y2UnitCost, y2AllocPct: l.y2AllocPct, y2Total: l.y2Total,
            y3Units: l.y3Units, y3UnitCost: l.y3UnitCost, y3AllocPct: l.y3AllocPct, y3Total: l.y3Total,
            y4Units: l.y4Units, y4UnitCost: l.y4UnitCost, y4AllocPct: l.y4AllocPct, y4Total: l.y4Total,
            y5Units: l.y5Units, y5UnitCost: l.y5UnitCost, y5AllocPct: l.y5AllocPct, y5Total: l.y5Total,
          })),
      },
    },
  });

  revalidatePath("/budget");
  return { id: budget.id };
}

/**
 * Normalises a (cadence, plannedMonths) pair from the client into a shape
 * the DB will accept: dedupe, sort, clamp to 1..12, enforce arity per cadence.
 * Throws on bad input — keep the server honest even if the UI guards.
 */
function normaliseCadence(
  cadence: BudgetLineCadence,
  plannedMonths: number[] | undefined,
): { cadence: BudgetLineCadence; plannedMonths: number[] } {
  if (cadence === "monthly") return { cadence, plannedMonths: [] };
  const cleaned = Array.from(new Set((plannedMonths ?? [])
    .map(m => Math.round(m))
    .filter(m => Number.isFinite(m) && m >= 1 && m <= 12)))
    .sort((a, b) => a - b);
  if (cadence === "one_time" && cleaned.length !== 1) {
    throw new Error("one_time cadence requires exactly one planned month (1..12)");
  }
  if (cadence === "seasonal" && cleaned.length < 2) {
    throw new Error("seasonal cadence requires at least two planned months");
  }
  return { cadence, plannedMonths: cleaned };
}

const STALE_LINE_MESSAGE = "This line changed elsewhere while you were editing it. Reload the budget and try again.";

/** Compare-and-swap fragment for a line write. Absent token = no check. */
function staleGuard(expectedUpdatedAt?: string) {
  return expectedUpdatedAt ? { updatedAt: new Date(expectedUpdatedAt) } : {};
}

/** Mark a shared draft as touched by the grantee, so a regeneration pass or a
 *  reclaim can tell whether any of their work is at stake. */
async function stampPartnerEdit(write: BudgetLineWrite) {
  if (write.capability !== "propose") return;
  await prisma.budget.update({ where: { id: write.budgetId }, data: { partnerEditedAt: new Date() } });
}

export async function updateLine(
  lineId: string,
  updates: {
    description?: string;
    // Inflation category (Salary/Other/Nil) — omit to leave unchanged. The
    // editor recomputes the out-year unit costs before sending.
    costCategory?: InflationType;
    // domain: pass null to mark the row as cross-cutting, string to attach it
    // to a specific domain card. Omit to leave unchanged.
    domain?: string | null;
    // Cadence: omit to leave unchanged. Pass cadence + plannedMonths together.
    cadence?: BudgetLineCadence;
    plannedMonths?: number[];
    y1Units?: number; y1UnitCost?: number; y1AllocPct?: number;
    y2Units?: number; y2UnitCost?: number; y2AllocPct?: number;
    y3Units?: number; y3UnitCost?: number; y3AllocPct?: number;
    y4Units?: number; y4UnitCost?: number; y4AllocPct?: number;
    y5Units?: number; y5UnitCost?: number; y5AllocPct?: number;
  },
  // Optimistic concurrency: the row's `updatedAt` as the caller last saw it.
  // Omit only from callers that have just read the row themselves.
  expectedUpdatedAt?: string,
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const write = await withBudgetLineWrite(session, { lineId });

  const line = await prisma.budgetLine.findUnique({
    where: { id: lineId },
    select: {
      budgetId: true,
      costCategory: true,
      y1Units: true, y1UnitCost: true, y1AllocPct: true,
      y2Units: true, y2UnitCost: true, y2AllocPct: true,
      y3Units: true, y3UnitCost: true, y3AllocPct: true,
      y4Units: true, y4UnitCost: true, y4AllocPct: true,
      y5Units: true, y5UnitCost: true, y5AllocPct: true,
    },
  });
  if (!line) throw new Error("Not found");

  // Merge the patch over the stored row before computing totals. Treating an
  // absent field as 0 would zero the year totals on any partial patch.
  const total = (u: number, c: number, a: number) => Math.round(u * c * a);
  const y1Total = total(updates.y1Units ?? line.y1Units, updates.y1UnitCost ?? line.y1UnitCost, updates.y1AllocPct ?? line.y1AllocPct);
  const y2Total = total(updates.y2Units ?? line.y2Units, updates.y2UnitCost ?? line.y2UnitCost, updates.y2AllocPct ?? line.y2AllocPct);
  const y3Total = total(updates.y3Units ?? line.y3Units, updates.y3UnitCost ?? line.y3UnitCost, updates.y3AllocPct ?? line.y3AllocPct);
  const y4Total = total(updates.y4Units ?? line.y4Units, updates.y4UnitCost ?? line.y4UnitCost, updates.y4AllocPct ?? line.y4AllocPct);
  const y5Total = total(updates.y5Units ?? line.y5Units, updates.y5UnitCost ?? line.y5UnitCost, updates.y5AllocPct ?? line.y5AllocPct);

  // Strip + re-validate the cadence pair so we never persist {one_time, []} etc.
  const { cadence: _c, plannedMonths: _pm, ...rest } = updates;
  const cadencePatch = updates.cadence !== undefined
    ? normaliseCadence(updates.cadence, updates.plannedMonths)
    : {};

  // A base (Year-1) unit-cost change marks the line as customised on this budget.
  const costChanged = updates.y1UnitCost !== undefined && Math.round(updates.y1UnitCost) !== Math.round(line.y1UnitCost);
  const { count } = await prisma.budgetLine.updateMany({
    where: { id: lineId, ...staleGuard(expectedUpdatedAt) },
    data: { ...rest, ...cadencePatch, y1Total, y2Total, y3Total, y4Total, y5Total, ...(costChanged ? { workingCustomised: true } : {}) },
  });
  if (count === 0) throw new Error(STALE_LINE_MESSAGE);
  if (costChanged) {
    await prisma.budgetLineCostHistory.create({
      data: { budgetLineId: lineId, oldCost: line.y1UnitCost, newCost: updates.y1UnitCost!, source: "line edit", changedById: session.user.id },
    });
  }
  await stampPartnerEdit(write);
  revalidatePath(`/budget/${line.budgetId}`);
  // Hand the new concurrency token back: the editor keeps its rows in local state
  // and would otherwise send a stale token on the very next edit of this line.
  const fresh = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { updatedAt: true } });
  return { updatedAt: fresh?.updatedAt.toISOString() };
}

/** History for a budget line's base unit cost, newest first. */
export async function getBudgetLineHistory(lineId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const line = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { budget: { select: { partnerId: true, grantPartnerId: true } } } });
  await requireBudgetAccess(session, line?.budget ?? null, "read");
  const rows = await prisma.budgetLineCostHistory.findMany({ where: { budgetLineId: lineId }, orderBy: { changedAt: "desc" }, take: 50 });
  const byId = new Map(
    (await prisma.user.findMany({
      where: { id: { in: [...new Set(rows.map(r => r.changedById).filter((v): v is string => !!v))] } },
      select: { id: true, name: true, email: true },
    })).map(u => [u.id, u.name ?? u.email])
  );
  return rows.map(r => ({
    id: r.id, oldCost: r.oldCost, newCost: r.newCost, source: r.source,
    changedBy: r.changedById ? (byId.get(r.changedById) ?? null) : null,
    changedAt: r.changedAt.toISOString(),
  }));
}

/**
 * Author a budget line's working: replace its component breakup and set the
 * base (Year-1) unit cost to the rollup. Later-year unit costs are scaled by the
 * same ratio so the line keeps its inflation shape. Totals recompute; the change
 * is logged. This is the budget-level mirror of the registry working editor.
 */
export async function saveBudgetLineComponents(
  lineId: string,
  rows: { label: string; spec?: string | null; qty: number; unitCost: number }[],
  derivation: string | null,
  expectedUpdatedAt?: string,
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const write = await withBudgetLineWrite(session, { lineId });
  const line = await prisma.budgetLine.findUnique({
    where: { id: lineId },
    select: {
      budgetId: true,
      y1Units: true, y1UnitCost: true, y1AllocPct: true,
      y2Units: true, y2UnitCost: true, y2AllocPct: true,
      y3Units: true, y3UnitCost: true, y3AllocPct: true,
      y4Units: true, y4UnitCost: true, y4AllocPct: true,
      y5Units: true, y5UnitCost: true, y5AllocPct: true,
    },
  });
  if (!line) throw new Error("Not found");

  const clean = rows
    .map(r => ({ label: (r.label ?? "").trim(), spec: (r.spec ?? "")?.toString().trim() || null, qty: Number(r.qty) || 0, unitCost: Number(r.unitCost) || 0 }))
    .filter(r => r.label.length > 0);
  const rollup = Math.round(clean.reduce((s, r) => s + r.qty * r.unitCost, 0));
  const deriv = derivation?.trim() || null;

  // Scale later years by the same ratio the edit applies to Year 1, preserving
  // the existing inflation curve. If Year-1 was 0, fall back to a flat rollup.
  const ratio = line.y1UnitCost > 0 ? rollup / line.y1UnitCost : 1;
  const scaled = (base: number) => (line.y1UnitCost > 0 ? Math.round(base * ratio) : rollup);
  const y1c = clean.length > 0 ? rollup : line.y1UnitCost;
  const y2c = clean.length > 0 ? scaled(line.y2UnitCost) : line.y2UnitCost;
  const y3c = clean.length > 0 ? scaled(line.y3UnitCost) : line.y3UnitCost;
  const y4c = clean.length > 0 ? scaled(line.y4UnitCost) : line.y4UnitCost;
  const y5c = clean.length > 0 ? scaled(line.y5UnitCost) : line.y5UnitCost;
  const total = (u: number, c: number, a: number) => Math.round(u * c * a);

  await prisma.$transaction(async (tx) => {
    await tx.budgetLineComponent.deleteMany({ where: { budgetLineId: lineId } });
    if (clean.length > 0) {
      await tx.budgetLineComponent.createMany({
        data: clean.map((r, i) => ({ budgetLineId: lineId, position: i, label: r.label, spec: r.spec, qty: r.qty, unitCost: r.unitCost })),
      });
    }
    const { count } = await tx.budgetLine.updateMany({
      where: { id: lineId, ...staleGuard(expectedUpdatedAt) },
      data: {
        derivation: deriv,
        workingCustomised: true,
        y1UnitCost: y1c, y1Total: total(line.y1Units, y1c, line.y1AllocPct),
        y2UnitCost: y2c, y2Total: total(line.y2Units, y2c, line.y2AllocPct),
        y3UnitCost: y3c, y3Total: total(line.y3Units, y3c, line.y3AllocPct),
        y4UnitCost: y4c, y4Total: total(line.y4Units, y4c, line.y4AllocPct),
        y5UnitCost: y5c, y5Total: total(line.y5Units, y5c, line.y5AllocPct),
      },
    });
    if (count === 0) throw new Error(STALE_LINE_MESSAGE);
    if (clean.length > 0 && Math.round(line.y1UnitCost) !== rollup) {
      await tx.budgetLineCostHistory.create({
        data: { budgetLineId: lineId, oldCost: line.y1UnitCost, newCost: rollup, source: "working editor", changedById: session.user!.id },
      });
    }
  });

  await stampPartnerEdit(write);
  revalidatePath(`/budget/${line.budgetId}`);
  const fresh = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { updatedAt: true } });
  return { updatedAt: fresh?.updatedAt.toISOString() };
}

export async function addLine(
  budgetId: string,
  data: {
    domain?: string;
    section: BudgetSection;
    description: string;
    costCategory: InflationType;
    unitType: string;
    y1Units?: number;
    y1UnitCost?: number;
    cadence?: BudgetLineCadence;
    plannedMonths?: number[];
    /** Multi-partner: which delivery partner this line belongs to (null = shared/Master). */
    deliveryPartnerId?: string | null;
  }
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const write = await withBudgetLineWrite(session, { budgetId });

  const budget = await prisma.budget.findUnique({
    where: { id: budgetId },
    select: {
      horizonMonths: true,
      applyInflation: true,
      inflationSalaryPct: true,
      inflationOtherPct: true,
      inflationNilPct: true,
      lines: { select: { position: true }, orderBy: { position: "desc" }, take: 1 },
    },
  });
  if (!budget) throw new Error("Not found");

  const ratePct =
    data.costCategory === "Salary" ? budget.inflationSalaryPct
    : data.costCategory === "Other" ? budget.inflationOtherPct
    : budget.inflationNilPct;
  const rate = budget.applyInflation ? ratePct / 100 : 0;

  const y1Units = data.y1Units ?? 0;
  const y1UnitCost = data.y1UnitCost ?? 0;

  const yearFactor = (k: number): number => {
    const full = Math.floor(budget.horizonMonths / 12);
    const tail = budget.horizonMonths - full * 12;
    if (k <= full) return 1;
    if (k === full + 1 && tail > 0) return tail / 12;
    return 0;
  };

  const bandData = (k: number) => {
    const factor = yearFactor(k);
    if (factor === 0) return { units: 0, cost: 0, total: 0 };
    const units = y1Units * factor;
    const cost  = Math.round(y1UnitCost * Math.pow(1 + rate, k - 1));
    return { units, cost, total: Math.round(units * cost) };
  };

  const b1 = { units: y1Units, cost: y1UnitCost, total: Math.round(y1Units * y1UnitCost * yearFactor(1)) };
  const b2 = bandData(2);
  const b3 = bandData(3);
  const b4 = bandData(4);
  const b5 = bandData(5);

  const nextPos = (budget.lines[0]?.position ?? 0) + 1;
  // Defaults: Capex section → one_time month 1, everything else → monthly.
  // Partner can override via the cadence picker in the add-line form.
  const fallbackCadence: BudgetLineCadence = data.section === "capex" ? "one_time" : "monthly";
  const cadencePatch = normaliseCadence(
    data.cadence ?? fallbackCadence,
    data.cadence ? data.plannedMonths : (data.section === "capex" ? [1] : []),
  );
  const line = await prisma.budgetLine.create({
    data: {
      budgetId,
      deliveryPartnerId: data.deliveryPartnerId ?? null,
      domain: data.domain,
      section: data.section,
      description: data.description,
      costCategory: data.costCategory,
      unitType: data.unitType,
      position: nextPos,
      isAutoGenerated: false,
      ...cadencePatch,
      y1Units: b1.units, y1UnitCost: b1.cost, y1AllocPct: 1, y1Total: b1.total,
      y2Units: b2.units, y2UnitCost: b2.cost, y2AllocPct: 1, y2Total: b2.total,
      y3Units: b3.units, y3UnitCost: b3.cost, y3AllocPct: 1, y3Total: b3.total,
      y4Units: b4.units, y4UnitCost: b4.cost, y4AllocPct: 1, y4Total: b4.total,
      y5Units: b5.units, y5UnitCost: b5.cost, y5AllocPct: 1, y5Total: b5.total,
    },
  });
  await stampPartnerEdit(write);
  revalidatePath(`/budget/${budgetId}`);
  return line;
}

export async function deleteLine(lineId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");
  const write = await withBudgetLineWrite(session, { lineId });

  const line = await prisma.budgetLine.findUnique({ where: { id: lineId }, select: { budgetId: true, isAutoGenerated: true } });
  if (!line) throw new Error("Not found");
  // BudgetLine cascades to BudgetReportLine and its notes, so a delete past
  // draft silently destroys filed actuals.
  if (write.status !== "draft") {
    throw new Error("This budget is no longer a draft — lines can't be deleted once it is finalised or approved.");
  }
  // The grantee may remove only lines they added; the generated skeleton is the
  // lead's, and a query on it belongs in a note, not a deletion.
  if (write.capability === "propose" && line.isAutoGenerated) {
    throw new Error("This line came with the draft — leave a note on it instead of deleting it.");
  }

  await prisma.budgetLine.delete({ where: { id: lineId } });
  await stampPartnerEdit(write);
  revalidatePath(`/budget/${line.budgetId}`);
}

/** Edit a delivery partner's name, shared-cost %, or GrantPartner registry
 *  link (multi-partner budgets). When grantPartnerId is passed, the target
 *  registry row must live in the same city as the budget — mirrors the
 *  invariant on Budget.grantPartnerId. Pass `null` to unlink. */
export async function updateDeliveryPartner(
  partnerId: string,
  updates: { name?: string; sharedPct?: number; grantPartnerId?: string | null },
) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const dp = await prisma.budgetDeliveryPartner.findUnique({
    where: { id: partnerId },
    select: { budgetId: true, budget: { select: { partnerId: true, grantPartnerId: true, city: true } } },
  });
  await requireBudgetAccess(session, dp?.budget ?? null, "update");
  if (!dp) throw new Error("Not found");

  if (updates.grantPartnerId) {
    const gp = await prisma.grantPartner.findUnique({
      where: { id: updates.grantPartnerId },
      select: { city: true },
    });
    if (!gp || gp.city !== dp.budget.city) throw new Error("Partner is not in this budget's city");
  }

  await prisma.budgetDeliveryPartner.update({
    where: { id: partnerId },
    data: {
      ...(updates.name !== undefined ? { name: updates.name.trim() || "Partner" } : {}),
      ...(updates.sharedPct !== undefined && Number.isFinite(updates.sharedPct) ? { sharedPct: updates.sharedPct } : {}),
      ...(updates.grantPartnerId !== undefined ? { grantPartnerId: updates.grantPartnerId } : {}),
    },
  });
  revalidatePath(`/budget/${dp.budgetId}`);
}

export async function finalizeBudget(budgetId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true, grantPartnerId: true, partnerEditState: true } });
  await requireBudgetAccess(session, budget, "update");
  if (!budget) throw new Error("Not found");
  assertPartnerEditClosed(budget.partnerEditState, "finalised");

  await prisma.budget.update({ where: { id: budgetId }, data: { status: "final" } });
  revalidatePath(`/budget/${budgetId}`);
}

/** Inverse of finalizeBudget: back to draft so lines can move again. Approved
 *  budgets stay put — their report slots are already generated against these
 *  lines, and reopening would let the figures drift out from under filed reports. */
export async function reopenBudget(budgetId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true, grantPartnerId: true, status: true } });
  await requireBudgetAccess(session, budget, "update");
  if (!budget) throw new Error("Not found");
  if (budget.status === "draft") return;
  if (budget.status === "approved") throw new Error("This budget is approved and has report slots against it — it can't be reopened.");

  await prisma.budget.update({ where: { id: budgetId }, data: { status: "draft" } });
  revalidatePath(`/budget/${budgetId}`);
}

export async function deleteBudget(budgetId: string) {
  const session = await auth();
  if (!session?.user?.id) throw new Error("Not authenticated");

  const budget = await prisma.budget.findUnique({ where: { id: budgetId }, select: { partnerId: true, grantPartnerId: true } });
  await requireBudgetAccess(session, budget, "delete");

  await prisma.budget.delete({ where: { id: budgetId } });
  // Refresh the city list (where the delete button lives) in place instead of
  // yanking the user back to the top-level /budget landing.
  revalidatePath("/budget");
  revalidatePath("/budget/city/[city]", "page");
  revalidatePath("/budget/dashboard");
}
